
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;

CREATE TABLE IF NOT EXISTS product_db.category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Alterado para BIGINT para consistência e escalabilidade
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100),
    parent_id BIGINT REFERENCES product_db.category(id) ON DELETE SET NULL
);